digitalocean/go-qemu

hypervisor/hypervisor.go
hypervisor/hypervisor_test.go
hypervisor/libvirt.go

Paves the way for `hypervisor.SocketDriver` or similar.
r: @benlemasurier 
Fixes #12.

hypervisor: make Hypervisor a struct, introduce Driver interface

---

hypervisor/hypervisor.go

Fixes a bug that didn't apply to the libvirt driver, but does to the QMP socket driver.
r: @benlemasurier

hypervisor: call qmp.Monitor.Connect where needed

---

hypervisor/libvirt.go
internal/shellexec/shellexec.go
internal/shellexec/shellexec_test.go
qmp/libvirt.go

This way, we can test interactions that shell out as well.
Supersedes #22.
r: @benlemasurier

internal/shellexec: new package to wrap shelling out, add plumbing

---

hypervisor/socket.go

Since there isn't a great autodetection mechanism for a bunch of different QEMU monitor sockets, I'm requiring manual entry for the time being.
Fixes #14

hypervisor: add SocketDriver type

---

example_test.go

Confirmed to work with a local `godoc` instance.
Fixes #27.

qemu: fix godoc output for ExampleNewDomain

---

hypervisor/libvirt.go
internal/shellexec/shellexec.go
internal/shellexec/shellexec_test.go
qmp/libvirt.go

internal/shellexec: split out Preparer interface from Command

---

qmp/libvirtrpc/rpc.go
qmp/libvirtrpc/rpc_test.go

This adds a new QMP monitor that makes use of libvirt's RPC protocol.
resources:
- https://libvirt.org/internals/rpc.html
- https://www.berrange.com/posts/2011/11/30/watching-the-libvirt-rpc-protocol-using-systemtap/
- libvirt source:
- src/remote/remote_protocol.x
- wireshark libvirt dissector
- libvirt: `./configure --with-wireshark-dissector ...`
TODO:
- Connection keep-alive (PING/PONG) while event monitor is active
A note on testing:
I've tried to emulate the exact responses as sent by libvirt, hence the raw bytes. This could be clarified by XDR encoding predefined types. However, I've seen small inconsistencies between the encoding provided by our XDR package and libvirt. This method should ensure we're always testing against known-good data as sent by libvirt.
fixes #9

Pure golang QMP Monitor over libvirt RPC

---

qmp/libvirtrpc/rpc_test.go

Simplifies the tests and should allow us to pass tests on non-container builds on Travis.

libvirtrpc: replace test TCP listener with net.Pipe

---

hypervisor/rpc.go
qmp/libvirtrpc/rpc.go

This adds a new hypervisor Driver backed by libvirt RPC.
The most notable change here is that libvirtrpc.Disconnect() now closes the underlying net.Conn. I've included the change here in order to keep the driver relatively simple. However, we'll need to make this change either way. It turns out that when Disconnect() is called, libvirt closes its half of the connection. Not closing our half provides a confusing interface for the caller. If the connection were to be reused,
subsequent calls would fail with a TCP RST.
Fixes #42

hypervisor: adds hypervisor Driver for RPC

---

qmp/libvirtrpc/rpc.go

This fixes a bug in `Events()` that caused a panic when closing invalid event streams. The event monitor was failing to verify that event stream registration had successfully returned.

libvirtrpc: check event stream result for errors

---

internal/shellexec/shellexec.go

We need access to something that reports whether a command has exited to improve error handling. This adds `Exited()` to the Command interface.

internal/shellexec: adds Exited() to Command

---

internal/shellexec/shellexec.go
qmp/libvirt.go
qmp/libvirtrpc/rpc.go
qmp/qmp.go

Older versions of libvirt do not have support for event monitoring. This modifies the RPC and shellout QMP drivers to return `ErrEventsUnsupported` when we've detected a lack of support. This required error inspection for the RPC driver and an unfortunate catch-all for early terminated shellout commands.

qmp: return ErrEventsUnsupported for old versions of libvirt

---

block.go
domain.go
domain_test.go
mock_test.go

This modifies `listenAndServe()` to set a flag on the domain when event streaming is unsupported. The caller will then receive `qmp.ErrEventsNotSupported` when calling `Domain.Events()`.
This allows `NewDomain()` to gracefully return given that not all users are interested in events.
Fixes #62

qemu: gracefully handle unsupported event monitor

---

AUTHORS
hypervisor/hypervisor.go
hypervisor/libvirt.go
hypervisor/rpc.go
qmp/libvirtrpc/hypervisor.go
qmp/libvirtrpc/hypervisor_test.go
qmp/libvirtrpc/mock_test.go
qmp/libvirtrpc/rpc.go

This PR adds a Versioner interface to `hypervisor` and implements it for `LibvirtDriver` and `RPCDriver`.
cc @benlemasurier

Add ability to get version string from libvirt drivers

---

block_test.go
domain.go
domain_test.go
hypervisor/hypervisor.go
hypervisor/hypervisor_test.go
mock_test.go
version_test.go

Instead of adding an option to `hypervisor.Hypervisor` to disconnect individual domains, let's allow `qemu.Domain` to "own" its underlying `qmp.Monitor`, and handle disconnecting it when `Domain.Close()` is called.

qemu, hypervisor: Domain always disconnects underlying qmp.Monitor

---

domain.go
domain_test.go

IMO, we should remove any test that just checks for "returned an error" cases.  I've adopted a policy of only testing error paths when the error is handled in some way.

qemu: clean up query-block tests, remove some trivial tests

---

domain_test.go
version_test.go

Let's unify how we do testing in regard to monitor failures. This returns the test closure to a simple `interface{}` return type.

qemu: remove support for test domain monitor failures

---

block_test.go
domain_test.go

- TestBlockDevices
- moved this test to `domain_test.go`, `BlockDevices()` lives in `domain.go`
- TestBlockStats
- TestClose
- TestCommands
- TestScreendump

qemu: migrate a few more tests over to the new style

---

block_test.go
domain_test.go
version_test.go

This migrates all of our block tests (`block_test.go`) over to the new style of testing. In order to handle event generated block errors I had to re-add the ability for a `testMonitor` to return an error.

qemu: migrate all block tests to new style

---

domain_test.go

Addresses #101.
For locally-run tests, 10ms for event timeouts should be more than enough.
cc @mdlayher

go-qemu: reduce test timeouts by a factor of 100

---

examples/README.md
examples/domain_details/main.go
examples/domain_system_powerdown/main.go
examples/hypervisor_domain_list/main.go

I added 3 examples. Let me know if you'd like to change anything.

PR for Issue 78

---

internal/qmp-gen/templates/flatunion
qmp/raw/autogen.go

It's just one line, but IMO it's slightly cleaner.  The caller should not make any assumptions about the value of `ret` if `err != nil` anyway.
/cc @danderson for thoughts

internal/qmp-gen: slightly simplify json.Unmarshal error handling

---

internal/qmp-gen/types.go
qmp/raw/autogen.go
qmp/raw/spec.txt

Recent revisions of the spec have added more general documentation
(good!), but those are tripping up the code generator as potential
rogue datatype docstrings (bad!).
In practice, we still have a safety in place for that, because we
refuse to codegen a type definition that doesn't have a docstring.
So, we can safely ignore orphan docstrings, as long as we don't
ignore orphan definitions.

Be more lenient about isolated docstrings in the QMP spec.

---

qemu/domain.go
qemu/version_test.go
qmp/raw/autogen.go
qmp/raw/spec.txt

This is a more detailed version string than is returned by Version(), allowing callers to distinguish between patch builds.

domain: Add a function to get the qemu package version

---

qemu/string.gen.go
qmp/raw/autogen.go
qmp/raw/spec.txt
qmp/socket.go
qmp/socket_test.go

Hello! Awesome work here!
In our use case, we instruct Qemu to connect to our processes's socket instead of racing to connect to Qemu's generated socket. This is a big win for us in terms of concurrency since we no longer need to poll for Qemu's socket after spawning a Qemu process.
We pass `-chardev socket,id=qmp,path=qmp.sock` into Qemu instead of `-chardev socket,id=qmp,path=qmp.sock,server`
If this change makes sense, I am happy to refactor it and make the code more DRY. I can also add docs and tests for this change.

Create a SocketMonitor by listening for a Qemu connection.

---

hypervisor/example_test.go
internal/qmp-gen/main.go
qemu/block.go
qemu/example_test.go
qmp/raw/spec.txt

Previously, waitForSignal executed a command prior to listening on the event stream. If an event arrived prior to the commands return, the event stream would block forever.

qemu/block: fixes deadlock in waitForSignal

---

.travis.yml
qemu/domain.go
qemu/domain_test.go
qemu/string.gen.go

There's a race condition when a listener initiates a disconnect without continuing to receive on the previously returned unbuffered channel; thereby blocking the logic that does the disconnect.
The first commit is a unit test that demonstrates the scenario, the second is a relatively quick and dirty fix.

Drain channel on disconnect

---

qmp/rpc.go

Fixes API change https://github.com/digitalocean/go-libvirt/commit/e2a69bcd5bd163f61a7e222cf915101e7e11b1c6 
Fixes #167
Signed-off-by: Thomas Parrott <thomas.parrott@canonical.com>

qmp/rpc: Fix upstream API change

---

go.mod
go.sum
qmp/socket.go
qmp/socket_unix.go
qmp/socket_windows.go

This PR does two main things:
- Record the capabilities returned by QEMU at connection time (and make them available through `Capabilities`)
- Introduce a new `RunWithFile` function which behaves like `Run` but takes an `os.File` as an argument, using the out-of-band unix socket capability to send the file as part of the monitor command.
We're adding support for hibernate (dump state to disk) and for live migration to LXD and need this feature to send the migration target file descriptor over to QEMU.

[qmp] Add RunWithFile to socket client

---

qemu/block.go
qemu/block_test.go
qemu/domain.go
qemu/domain_test.go
qmp/rpc.go

The channel returned by `qmp.LibvirtRPCMonitor.Events` will now be closed
regardless of how the goroutine populating the channel exits.
Specifically, this channel was not being closed when the underlying channel
returned from `SubscribeQEMUEvents` was closed. This happens for various
reasons, but one important one is when the underlying libvirtd connection is
closed.
This change caused the `qemu.Domain.Events` to always return the default value
once the underlying monitor had closed, and so this code was reworked so that
this channel would also close.
The changes to `qemu.Domain` required some restructuring of some old,
unidiomatic Go code, but I have not changed the API signatures, nor the
semantics of using the code outside receiving a channel which will now close.
This was made …

In `Events` functions, always close the returned channel when done

---

qemu/domain_test.go
qmp/rpc_test.go
qmp/socket_test.go

These can make unit tests brittle depending on a number of factors that aren't controllable from the unit test suite. Rather than hard-coding these values in, let the test runner `go test -timeout` impose the timeout.

Remove uses of package time from unit tests (where feasible) 

---

.github/dependabot.yml

This altruistic automaton will automatically apply updates to the go.mod and propose them for merge.
This will be particularly helpful for consuming new changes from go-libvirt, since the libvirttest package is relied upon in this repo.

add dependabot automation

---

qmp/socket.go

Otherwise SocketMonitor.listen will leak since it will block trying to
send the io.EOF err through the channel to a listener that is no longer
listening.
To test this, I modified one of the test cases which goes through a
SocketMonitor.Connect,.Disconnect lifecycle to hang forever, like so:
diff --git a/qmp/socket_test.go b/qmp/socket_test.go
index d6eb4a1..c3484ed 100644
--- a/qmp/socket_test.go
+++ b/qmp/socket_test.go
@@ -32,6 +32,9 @@ import (
func TestSocketMonitorConnectDisconnect(t *testing.T) {
_, _, done := testSocket(t)
done()
+
+       var forever chan struct{}
+       <-forever
}
I did this instead of setting a breakpoint because the test suite would
exit the process too quickly.
Then I ran the test, waited a few seconds, and paused the program with
the debugger and looked to …

drain stream chan during Disconnect

---

qmp/socket.go

And not block forever if mon.stream not initialised yet.
Fixes #200
See https://github.com/lxc/lxd/issues/11892#issuecomment-1607086255

Allow Disconnect to be used to cancel ongoing Connect call
