digitalocean/go-qemu

README.md
=> README: add pre-production software warning

hypervisor/hypervisor_test.go
Adds a test for the fix included in #15 .
=> hypervisor: add test for fixed monitor connect bug

example_test.go
=> qemu: add ExampleNewDomain

mock_test.go
=> mock_test: refactor mockMonitor.Run into three methods

CONTRIBUTING.md
Let me know if I missed anything!
Fixes #3.
=> CONTRIBUTING: initial commit

AUTHORS
For additional contributors to add their names.
=> AUTHORS: add a Contributors section

hypervisor/libvirt.go, internal/shellexec/shellexec.go, internal/shellexec/shellexec_test.go, internal/virsh/virsh.go, internal/virsh/virsh_test.go, qmp/libvirt.go
=> internal/virsh: initial commit

domain.go, domain_test.go, mock_test.go, tempfile.go
=> qemu: add Domain.ScreenDump

qmp/libvirtrpc/rpc_test.go
Maintaining the correct response serial number within tests is becoming
too cumbersome. This modifies the mock libvirt server to reply with
sequential serial numbers injected into response payloads.
=> libvirtrpc: automatically determine response serial number

qmp/README.md
This adds a few words on the newly available socket and RPC drivers.
Fixes #57
=> qmp: update README.md

example_test.go
Updates example to match changes from https://github.com/digitalocean/go-qemu/pull/74.
=> example_test: update example; domain now closes monitor

domain_test.go
Initial work toward #70, just to make sure the pattern is sane.
=> qemu: example of new style of testing

domain_test.go, version_test.go
- modify `testMonitor.Run()` to allow the closure to return a `qmp.Monitor.Run()` failure.
- port `TestVersion()` to the new style
- port `TestSystemPowerdown()` to the new style
Maybe it's a bit much to include tests like `TestVersionMonitorFail()`? I can go either way. In the end I think tests that include these failure scenarios will be a good thing to have. On that note, I've dropped `TestVersionInvalidJSON()`. We can't perform these with the new style and they're a bit redundant anyway.
=> qmp: expand on new testing style

domain_test.go
- `TestSupported()`
- `TestSupportedFalse()`
- `TestSUpportedMonitorFailure()`
- `TestEventsUnsupported()`
=> qemu: convert a few more tests over to the new style

block.go, domain.go, domain_test.go, example_test.go, hypervisor/libvirt.go, hypervisor/rpc.go, qmp/libvirt.go, qmp/libvirt_test.go, qmp/qmp.go, qmp/rpc.go, qmp/rpc_test.go, qmp/socket.go, qmp/socket_test.go, version_test.go
=> qmp: rename types for consistency

domain_test.go
- `TestStatusRunning()`
- `TestStatusShutdown()`
- `TestEvents()`
- add mock `Events()` to `testMonitor{}`
=> qemu: migrate a few more tests over to new style

README.md
=> README: update to reflect current project status

CONTRIBUTING.md, README.md
=> CONTRIBUTING, README: add IRC channel information

AUTHORS
=> added my name and email to AUTHORS

qmp/qmptest/qmptest.go, qmp/qmptest/qmptest_test.go
=> qmp/qmptest: initial commit

example_test.go
=> qemu: use qmptest.NewMonitor in ExampleNewDomain

hypervisor/example_test.go
=> hypervisor: add ExampleNew

AUTHORS
=> AUTHORS: add myself.

internal/qmp-gen/templates/enum, qmp/raw/autogen.go
=> internal/qmp-gen: enum types implement fmt.Stringer

internal/qmp-gen/types.go, qmp/raw/autogen.go
A small cleanup to the code generator.  Mostly just giving it a try!
=> internal/qmp-gen: AIO is acronym

internal/qmp-gen/parse_test.go
Work in progress, but I think this is a good start.
Thoughts?
=> internal/qmp-gen: initial TestGenerate with StatusInfo type

internal/qmp-gen/generate.go, internal/qmp-gen/parse_test.go, internal/qmp-gen/templates/command, qmp/raw/autogen.go, qmp/raw/raw.go
=> internal/qmp-gen: generate implementations for the commands.

domain.go
=> qemu: use raw.Monitor in Domain, implement in Domain.Status

qmp/raw/autogen.go, qmp/raw/spec.txt
=> qmp/raw: update generated code

qemu/block.go, qemu/block_test.go
There have been changes to how libvirt creates snapshots, that make the
current go-qemu APIs unable to work on libvirt 6, since they relied
on using a device string that is no longer present.
Fortunately, the call sequence and arguments that work for libvirt 6
*also* work for libvirt 3.
Unfortunately, they require information specifically about the block job
being cancelled, so the API changes slightly.
Block jobs were being completed/cancelled on the BlockDevice,
but the information used to identify them in libvirt6 is not the
BlockDevice.Device, but the BlockJob.Device, so move the methods to the
BlockJob.
See:
- https://www.mail-archive.com/qemu-discuss@nongnu.org/msg05225.html
=> Snapshot portability across libvirt 3 and 6

internal/qmp-gen/templates/simpleunion, qmp/raw/autogen.go, qmp/raw/raw_test.go
Re-posting #173 with authorship intact to run against CI to avoid bothering the original author with a request to rebase after such a long time of no other activity on the PR.
I verified the included test fixes the crasher.
Closes #173
=> Fix `simpleunion` marshall
